# Generated by Django 5.1.7 on 2025-03-10 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='shipment',
            table='shipment',
        ),
        migrations.AlterModelTable(
            name='shipmentitem',
            table='shipment_item',
        ),
    ]
