# Generated by Django 5.1.7 on 2025-03-21 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_approved_by_alter_orderitem_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='orderitem',
            table='order_item',
        ),
    ]
