# Generated by Django 5.1.7 on 2025-03-23 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_order_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='orderitem',
            table='orders_items',
        ),
    ]
