# Generated by Django 5.1.7 on 2025-03-11 10:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_product_critical_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='critical_quantity',
            field=models.PositiveIntegerField(default=10, editable=False, validators=[django.core.validators.MinValueValidator(10)]),
        ),
    ]
