# Generated by Django 5.1.7 on 2025-03-11 11:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_product_critical_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='critical_quantity',
            field=models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(30)]),
        ),
    ]
